Config.Companies = {
    Enabled = true,
    PageSize = 20,
    MaximumPageSize = 50,
    MaximumOpenRequestsPerSim = 5,
    MaximumServices = 25,
    MaximumRequestMedia = 3,
    SubjectMaxLength = 120,
    RequestBodyMaxLength = 2000,
    MessageMaxLength = 2000,
    ProfileDescriptionMaxLength = 1000,
    DistrictMaxLength = 80,
    AddressMaxLength = 160,
    ServiceTitleMaxLength = 80,
    ServiceDescriptionMaxLength = 500,
    ServicePriceMaxLength = 80,
    AnnouncementTitleMaxLength = 120,
    AnnouncementBodyMaxLength = 1000,
    AvailabilityMaximumSeconds = 24 * 60 * 60,
    AnnouncementMaximumSeconds = 30 * 24 * 60 * 60,
    RetentionDays = 180,
    RateLimits = {
        Read = 120,
        Search = 60,
        CreateRequest = 5,
        Message = 30,
        RequestAction = 30,
        Profile = 12,
        CallAvailability = 30,
    },
    CallRouting = {
        MaxAttempts = 3,
        RingSeconds = 10,
    },
    Categories = {
        "public_services",
        "vehicles",
        "transport",
    },
    Statuses = {
        new = true,
        assigned = true,
        in_progress = true,
        waiting_customer = true,
        completed = true,
        cancelled = true,
    },
    AvailabilityStatuses = {
        available = true,
        busy = true,
        closed = true,
    },
    Definitions = {
        police = {
            Job = "police",
            Name = "Los Santos Police Department",
            Category = "public_services",
            Public = true,
            Emergency = true,
            Verified = true,
            Icon = "shield",
            Description = "Public safety, emergency response, and police services.",
            DefaultAvailability = "closed",
            AcceptsRequests = false,
            District = "Mission Row",
            LocationLabel = "Mission Row Police Station",
            Address = "Mission Row Police Station",
            Location = vector3(425.1, -979.5, 30.7),
            ServiceLine = {
                Number = "9110000000",
                AutoContact = true,
                CanCall = true,
                CanMessage = false,
                Routing = "round_robin",
                MinimumGrade = 0,
            },
            Permissions = {
                WorkQueue = 0,
                Availability = 1,
                Assign = 2,
                Profile = 3,
                Hours = 3,
                Services = 3,
                Announcement = 3,
            },
            Services = {},
        },
        ambulance = {
            Job = "ambulance",
            Name = "Emergency Medical Services",
            Category = "public_services",
            Public = true,
            Emergency = true,
            Verified = true,
            Icon = "medical",
            Description = "Emergency medical response and patient care.",
            DefaultAvailability = "closed",
            AcceptsRequests = false,
            District = "Pillbox Hill",
            LocationLabel = "Pillbox Hill Medical Center",
            Address = "Pillbox Hill Medical Center",
            Location = vector3(307.2, -595.3, 43.3),
            ServiceLine = {
                Number = "9120000000",
                AutoContact = true,
                CanCall = true,
                CanMessage = false,
                Routing = "round_robin",
                MinimumGrade = 0,
            },
            Permissions = {
                WorkQueue = 0,
                Availability = 1,
                Assign = 2,
                Profile = 3,
                Hours = 3,
                Services = 3,
                Announcement = 3,
            },
            Services = {},
        },
        fire = {
            Job = "fire",
            Name = "Los Santos Fire Department",
            Category = "public_services",
            Public = true,
            Emergency = true,
            Verified = true,
            Icon = "flame",
            Description = "Fire response, rescue, and public safety services.",
            DefaultAvailability = "closed",
            AcceptsRequests = false,
            District = "El Burro Heights",
            LocationLabel = "Capital Boulevard Fire Station",
            Address = "Capital Boulevard Fire Station",
            Location = vector3(1200.6, -1473.6, 34.9),
            ServiceLine = {
                Number = "9130000000",
                AutoContact = true,
                CanCall = true,
                CanMessage = false,
                Routing = "round_robin",
                MinimumGrade = 0,
            },
            Permissions = {
                WorkQueue = 0,
                Availability = 1,
                Assign = 2,
                Profile = 3,
                Hours = 3,
                Services = 3,
                Announcement = 3,
            },
            Services = {},
        },
        mechanic = {
            Job = "mechanic",
            Name = "Los Santos Customs",
            Category = "vehicles",
            Public = true,
            Emergency = false,
            Verified = true,
            Icon = "wrench",
            Description = "Vehicle diagnostics, repairs, and roadside assistance.",
            DefaultAvailability = "closed",
            AcceptsRequests = true,
            District = "Burton",
            LocationLabel = "Los Santos Customs",
            Address = "Carcer Way",
            Location = vector3(-337.3, -136.9, 39.0),
            ServiceLine = {
                Number = "5550101000",
                AutoContact = true,
                CanCall = true,
                CanMessage = false,
                Routing = "round_robin",
                MinimumGrade = 0,
            },
            Permissions = {
                WorkQueue = 0,
                Availability = 1,
                Assign = 2,
                Profile = 3,
                Hours = 3,
                Services = 3,
                Announcement = 3,
            },
            Services = {
                {
                    Id = "mechanic-repair",
                    Title = "Vehicle repair",
                    Description = "Diagnostics and repairs for road vehicles.",
                    Price = "Price after inspection",
                    RequestsEnabled = true,
                },
                {
                    Id = "mechanic-towing",
                    Title = "Roadside assistance",
                    Description = "Assistance for disabled vehicles.",
                    Price = "Price by distance",
                    RequestsEnabled = true,
                },
            },
        },
        taxi = {
            Job = "taxi",
            Name = "Downtown Cab Co.",
            Category = "transport",
            Public = true,
            Emergency = false,
            Verified = true,
            Icon = "car",
            Description = "Staffed taxi rides throughout Los Santos and Blaine County.",
            DefaultAvailability = "closed",
            AcceptsRequests = true,
            District = "East Vinewood",
            LocationLabel = "Downtown Cab Co.",
            Address = "Tangerine Street",
            Location = vector3(895.0, -179.2, 74.7),
            ServiceLine = {
                Number = "5550102000",
                AutoContact = true,
                CanCall = true,
                CanMessage = false,
                Routing = "round_robin",
                MinimumGrade = 0,
            },
            Permissions = {
                WorkQueue = 0,
                Availability = 1,
                Assign = 2,
                Profile = 3,
                Hours = 3,
                Services = 3,
                Announcement = 3,
            },
            Services = {
                {
                    Id = "taxi-ride",
                    Title = "Taxi ride",
                    Description = "Request a staffed taxi service.",
                    Price = "Metered fare",
                    RequestsEnabled = true,
                },
            },
        },
    },
}
